config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'

  # Session Handling
  get :login,  to: 'sessions#new'
  get :logout, to: 'sessions#destroy'
  post :login, to: 'sessions#create'

  # Registration Handling
  get :register, to: 'users#new'
  post :register, to: 'users#create'

  # Other Resources
  resources :lobbies, path: :l, only: [:index, :new, :show] do
    resources :messages, only: [:create, :index], shallow: true
    resources :lobby_users, only: [:index, :show, :destroy], shallow: true

    resources :games, only: [:create, :show], shallow: true do
      resources :players, only: [:create], shallow: true do
        resources :cards, only: [:create, :index], controller: 'players/cards'
      end

      resources :rounds, only: [:create, :show], shallow: true do
        resources :cards, only: [:create, :update], controller: 'rounds/cards'
        resource :winner, only: [:create], controller: 'rounds/winners'
      end
    end
  end

  namespace :admin do
    root to: 'dashboard#show', as: :dashboard

    resources :expansions do
      resources :cards, only: [:new, :create, :edit, :update, :destroy], shallow: true
    end

    resources :users
  end
end

app/models/expansion.rb
# == Schema Information
#
# Table name: expansions
#
#  id         :integer          not null, primary key
#  name       :string
#  uuid       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Expansion < ApplicationRecord
  include HasGuid

  has_many :cards, class_name: Card

  scope :default, -> { all }

  has_guid :uuid, type: :uuid

  validates_presence_of :name

  self.per_page = 10

  scoped_search on: :name
end

app/controllers/admin/expansions_controller.rb
class Admin::ExpansionsController < AdminController
  before_action :get_expansion, only: [:show, :edit, :update, :destroy]

  def index
    @expansions = filter_scope Expansion.all
    respond_with :admin, @expansions
  end

  def new
    @expansion = Expansion.new
    respond_with :admin, @expansion
  end

  def show
    @cards = filter_scope @expansion.cards, skip_params: ['id']
  end

  def edit; end

  def create
    @expansion = Expansion.create(expansion_params)
    respond_with :admin, @expansion
  end

  def update
    @expansion.update_attributes(expansion_params)
    respond_with :admin, @expansion
  end

  def destroy
    @expansion.destroy!
    respond_with :admin, @expansion
  end

  private

  def get_expansion
    @expansion = Expansion.find_by!(uuid: params[:id])
  end

  def expansion_params
    params.require(:expansion).permit(:name)
  end
end

app/views/admin/expansions/_form.html.haml
.card
  = simple_form_for [:admin, @expansion] do |f|
    .card-content
      = f.input :name
    .card-action
      = f.button :submit

app/views/admin/expansions/edit.html.haml
= action_button 'cancel', admin_expansion_path(@expansion), class: 'grey', tooltip: 'Cancel'
= record_header 'Edit Expansion'

.container
  = render 'form'

app/views/admin/expansions/index.html.haml
= action_button 'add', new_admin_expansion_path, tooltip: 'New Expansion'

= record_header 'Expansions',
    'Manage collections of cards in the game. These should reflect physical cards, also.'

= results_message @expansions

.container
  .row
    - @expansions.each do |expansion|
      .col.s12.m6
        .card
          .card-content
            .card-title.truncate= expansion.name

            %ul.counts
              %li
                = link_to '#' do
                  .count= expansion.cards.fools.count
                  Fools
              %li
                = link_to '#' do
                  .count= expansion.cards.crisis.count
                  Crisis
              %li
                = link_to '#' do
                  .count= expansion.cards.bad_decisions.count
                  Decisions
              %li
                = link_to '#' do
                  .count= expansion.cards.stories.count
                  Stories

          .card-action
            = link_to "#{expansion.cards.count} Cards", admin_expansion_path(expansion)
            = link_to 'Edit', admin_expansion_path(expansion), class: 'right'


  .center.margin-top-lg= will_paginate @expansions

app/views/admin/expansions/new.html.haml
= action_button 'cancel', admin_expansions_path, class: 'grey', tooltip: 'Cancel'
= record_header 'New Expansion'

.container
  = render 'form'

app/views/admin/expansions/show.html.haml
= action_button 'edit', edit_admin_expansion_path(@expansion), tooltip: 'Edit Expansion' do
  = action_button_child 'delete', admin_expansion_path(@expansion), tooltip: 'Delete Expansion', method: :delete, class: 'black'
  = action_button_child 'add', new_admin_expansion_card_path(@expansion), tooltip: 'Add Cards', class: 'teal'

= record_header @expansion.name, search: 'Search cards...' do
  = scope_tabs :type, model: @expansion.cards,
                      default: 'All Cards',
                      'Card::Fool' => 'Fools',
                      'Card::Crisis' => 'Crisis',
                      'Card::BadDecision' => 'Bad Decisions',
                      'Card::Story' => 'Stories'

= results_message @cards

.container
  .row.masonry
    - @cards.each do |card|
      .col.s6.m4.l3
        = link_to card.to_html, edit_admin_card_path(card)

  .center= will_paginate @cards