config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'

  # Session Handling
  get :login,  to: 'sessions#new'
  get :logout, to: 'sessions#destroy'
  post :login, to: 'sessions#create'

  # Registration Handling
  get :register, to: 'users#new'
  post :register, to: 'users#create'

  # Other Resources
  resources :lobbies, path: :l, only: [:index, :new, :show] do
    resources :messages, only: [:create, :index], shallow: true
    resources :lobby_users, only: [:index, :show, :destroy], shallow: true

    resources :games, only: [:create, :show], shallow: true do
      resources :players, only: [:create], shallow: true do
        resources :cards, only: [:create, :index], controller: 'players/cards'
      end

      resources :rounds, only: [:create, :show], shallow: true do
        resources :cards, only: [:create, :update], controller: 'rounds/cards'
        resource :winner, only: [:create], controller: 'rounds/winners'
      end
    end
  end

  namespace :admin do
    root to: 'dashboard#show', as: :dashboard

    resources :expansions do
      resources :cards, only: [:new, :create, :edit, :update, :destroy], shallow: true
    end

    resources :users
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string
#  email           :string
#  display_name    :string
#  password_digest :string
#  uuid            :string
#  admin           :boolean
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  include HasGuid

  has_and_belongs_to_many :expansions,
                          join_table: :user_expansions

  has_and_belongs_to_many :friends,
                          class_name: User,
                          join_table: :friendships,
                          foreign_key: :user_id,
                          association_foreign_key: :friend_user_id

  has_many :lobby_users
  has_many :lobbies, through: :lobby_users

  has_guid :uuid, type: :uuid

  validates_presence_of :username
  validates_presence_of :email
  validates_presence_of :display_name
  validates_uniqueness_of :username, case_sensitive: false
  validates_uniqueness_of :email, case_sensitive: false

  validates_format_of :username, with: /\A[^_-].*[^_-]\z/, message: 'can not start or end with _ or -'
  validates_format_of :username, with: /\A[a-z0-9][a-z0-9_-]+[a-z0-9]\z/i, message: 'can only be letters, numbers, _ and -'
  validates_format_of :email, with: /@/, message: 'must have an @ sign'

  has_secure_password

  scope :admins, -> { where(admin: true) }

  def avatar_url
    GravatarImageTag.gravatar_url self.email
  end

  def online!
    Rails.logger.info "Online: #{self.username}"

    self.friends.find_each do |friend|
      friend.broadcast online: self.as_json
    end
  end

  def offline!
    Rails.logger.info "Offline: #{self.username}"

    self.friends.find_each do |friend|
      friend.broadcast offline: self.as_json
    end
  end

  def as_json
    ActiveModelSerializers::SerializableResource.new(self).as_json
  end

  def broadcast(data)
    UserChannel.broadcast_to self, data
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  before_action :get_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = filter_scope User.all
    respond_with :admin, @user
  end

  def new
    @user = User.new
    respond_with :admin, @user
  end

  def show; end
  def edit; end

  def create
    @user = User.create(user_params)
    respond_with :admin, @user
  end

  def update
    @user.update_attributes(user_params)
    respond_with :admin, @user
  end

  def destroy
    @user.destroy
    respond_with :admin, @suer
  end

  private

  def get_user
    @user = User.find_by!(uuid: params[:id])
  end

  def user_params
    params.require(:user).permit(:display_name, :email, :username, :password, :password_confirmation, :admin)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)

    if @user.save
      slack_message "New user: #{@user.username}", username: @user.username, email: @user.email, display_name: @user.display_name
      log_in @user
      redirect_to lobbies_path, flash: { notice: t('session.register_success') }
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :display_name, :email, :password, :password_confirmation)
  end
end

app/views/admin/users/_form.html.haml
.card
  = simple_form_for [:admin, @user] do |f|
    .card-content
      .row
        .col.s12.m6
          = f.input :display_name
          = f.input :username
          = f.input :email
        .col.s12.m6
          = f.input :password
          = f.input :password_confirmation
          .caption.margin-bottom-md Permissions
          = f.input :admin
    .card-action
      = f.button :submit

app/views/admin/users/edit.html.haml
= action_button 'cancel', admin_user_path(@user), class: 'grey', tooltip: 'Cancel'
= record_header 'Edit User', search: false

.container
  = render 'form'

app/views/admin/users/index.html.haml
= action_button 'add', new_admin_user_path, tooltip: 'New User'
= record_header 'Users', search: true
= results_message @users

.container
  .row
    - @users.each do |user|
      .col.s12.m6.l4
        .card
          .card-content
            .avatar= image_tag user.avatar_url, class: 'circle'
            .card-title.truncate= user.display_name
          .card-action
            = link_to 'Edit', admin_user_path(user)

app/views/admin/users/new.html.haml
= action_button 'cancel', admin_users_path, class: 'grey', tooltip: 'Cancel'
= record_header 'New User'

.container
  = render 'form'

app/views/admin/users/show.html.haml
= action_button 'edit', edit_admin_user_path(@user), tooltip: 'Edit User' do
  = action_button_child 'delete', admin_user_path(@user), tooltip: 'Delete User', method: :delete

= record_header @user.display_name, @user.uuid, search: false