config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'

  # Session Handling
  get :login,  to: 'sessions#new'
  get :logout, to: 'sessions#destroy'
  post :login, to: 'sessions#create'

  # Registration Handling
  get :register, to: 'users#new'
  post :register, to: 'users#create'

  # Other Resources
  resources :lobbies, path: :l, only: [:index, :new, :show] do
    resources :messages, only: [:create, :index], shallow: true
    resources :lobby_users, only: [:index, :show, :destroy], shallow: true

    resources :games, only: [:create, :show], shallow: true do
      resources :players, only: [:create], shallow: true do
        resources :cards, only: [:create, :index], controller: 'players/cards'
      end

      resources :rounds, only: [:create, :show], shallow: true do
        resources :cards, only: [:create, :update], controller: 'rounds/cards'
        resource :winner, only: [:create], controller: 'rounds/winners'
      end
    end
  end

  namespace :admin do
    root to: 'dashboard#show', as: :dashboard

    resources :expansions do
      resources :cards, only: [:new, :create, :edit, :update, :destroy], shallow: true
    end

    resources :users
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  include CollectionHelper
  include SlackHelper

  respond_to :json, :html, :js

  protect_from_forgery with: :exception

  rescue_from Exception, with: :internal_server_error
  rescue_from Exceptions::RuleViolation, with: :rule_violation

  private

  def internal_server_error(e)
    if Rails.configuration.x.slack['post_exceptions']
      slackify_exception e, current_user, request
    end

    raise e
  end

  def rule_violation(e)
    Rails.logger.warn e.inspect
    render json: { error: e.message }, status: :bad_request
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def toast(level_or_hash=:notice, message='', options={})
    if level_or_hash.is_a? Hash
      message = level_or_hash.values.first
      level_or_hash = level_or_hash.keys.first
    end

    flash_map = {
        notice: 'green',
        info:   'blue',
        warn:   'yellow',
        error:  'red'
    }

    klass = flash_map[level_or_hash.to_sym] || level_or_hash.to_s

    if options[:no_wrapper]
      <<-JAVASCRIPT.html_safe
        Materialize.toast("#{escape_javascript message}", 5000, "#{klass}")
      JAVASCRIPT
    else
      <<-HTML.html_safe
        <script type="text/javascript">
            Materialize.toast("#{escape_javascript message}", 5000, "#{klass}")
        </script>
      HTML
    end
  end

  def body_class(klass)
    content_for(:body_class, klass)
  end

  def no_side_nav
    content_for(:no_side_nav, true)
  end
end

app/views/application/_content.html.haml
%main= yield

app/views/application/_header.html.haml
-#%header
  %nav
    .nav-wrapper
      - unless meta_tags[:title]
        = link_to '#!', class: 'brand-logo center' do
          = image_tag 'logos/logo-full_600-white.png'

      %ul
        %li= link_to material_icon('menu'), '#', data: { activates: 'slide-out' }, class: 'button-collapse'

        - if meta_tags[:title]
          %li.page-title
            .title.truncate= meta_tags[:title]

      %ul.right
        - if logged_in?
          %li= link_to material_icon('exit_to_app'), logout_path
        - else
          %li= link_to t('session.login'), login_path, class: 'btn waves-effect waves-light red darken-2'
        %li= link_to material_icon('more_vert'), '#!'

app/views/application/_side_nav.html.haml
%ul#slide-out.side-nav{class: ('fixed' if params[:controller] =~ /^admin/)}
  %li
    .userView
      - if logged_in?
        .background
          = image_tag 'logos/logo-full_600-white.png'

        = link_to '#!avatar' do
          = image_tag current_user.avatar_url, class: 'circle'

        = link_to '#!name' do
          %span.white-text.name= current_user.display_name

        = link_to '#!email' do
          %span.white-text.email= current_user.email

      - else
        = link_to t('session.login'), login_path, class: 'btn'

  %li= link_to material_icon('chat', 'Game Lobbies'), lobbies_path

  - if logged_in?
    %li= link_to material_icon('supervisor_account', 'Friends'), '#!'

    - if Lobby.for_user(current_user).any?
      %li
        %a.subheader Your Games

      - Lobby.for_user(current_user).each do |lobby|
        %li= link_to material_icon('chat', lobby.name), lobby_path(lobby)

  - if current_user&.admin?
    %li.divider
    %li= link_to 'Admin', '#', class: 'subheader'
    %li= link_to material_icon('dashboard', 'Dashboard'), admin_dashboard_path
    %li= link_to material_icon('addon', 'Expansions'), admin_expansions_path
    %li= link_to material_icon('user', 'Users'), admin_users_path

app/views/application/create.js.erb
<% flash.each do |level, message| %>
  <%= toast level, message, no_wrapper: true %>
<% end %>